title: WoLLIC 2025 @ Porto.
description: 31th Workshop on Logic, Language, Information and Computation

baseurl: 
url: https://wollic2025.github.io

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: DCC@FCUP
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  